[project]
name = "camp-scoreboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "colorgram-py>=1.2.0",
    "dotenv>=0.9.9",
    "fastapi>=0.139.0",
    "gspread>=5.12.4",
    "logging>=0.4.9.6",
    "pandas>=3.0.3",
    "pillow>=12.3.0",
    "st-gsheets-connection>=0.1.0",
    "streamlit>=1.59.0",
    "uvicorn>=0.50.2",
]
